# HTTP redirect to HTTPS
server {
    listen               80;
    server_name          pma.sftest2.my;
    return               301 https://$host$request_uri;
}

server {
    listen              443 ssl;
    ssl_certificate     /www/sftest2/config/ssl/localhost.crt;
    ssl_certificate_key /www/sftest2/config/ssl/localhost.key;

    server_name         pma.sftest2.my;

    access_log          /var/log/nginx/pma.access.log;
    error_log           /var/log/nginx/pma.error.log;
    root                /usr/share/phpmyadmin;
    index               index.php;
    charset             utf-8;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_param   SCRIPT_FILENAME   $document_root$fastcgi_script_name;
        fastcgi_param   SCRIPT_NAME       $fastcgi_script_name;
        fastcgi_param   PATH_INFO         $fastcgi_path_info;
        fastcgi_pass    unix:/run/php/php8.3-fpm.sock;
        include         fastcgi_params;
    }
}
