security:
    password_hashers:
        Symfony\Component\Security\Core\User\InMemoryUser: 'plaintext'

    providers:
        app_users:
            memory:
                users:
                    admin: { password: 'admin', roles: ['ROLE_SUPER_ADMIN'] }

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        main:
            lazy: true
            provider: app_users
            http_basic: ~

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
