sonata_admin:
    options:
        html5_validate:  true     # enable or disable html5 form validation
        confirm_exit:    true     # enable or disable a confirmation before navigating away
        js_debug:        false    # enable or disable to show javascript debug messages
        use_select2:     true     # enable or disable usage of the Select2 jQuery library
        use_icheck:      true     # enable or disable usage of the iCheck library
        use_bootlint:    false    # enable or disable usage of Bootlint
        use_stickyforms: true     # enable or disable the floating buttons
        form_type:       standard # can also be 'horizontal'

    templates:
        edit:                       '@SonataAdmin/CRUD/edit.html.twig'
        tab_menu_template:          '@SonataAdmin/Core/tab_menu_template.html.twig'
        list:                       '@SonataAdmin/CRUD/list.html.twig'
        action:                     '@SonataAdmin/CRUD/action.html.twig'
        select:                     '@SonataAdmin/CRUD/list__select.html.twig'
        list_block:                 '@SonataAdmin/Block/block_admin_list.html.twig'
        short_object_description:   '@SonataAdmin/Helper/short-object-description.html.twig'
        batch:                      '@SonataAdmin/CRUD/list__batch.html.twig'
        inner_list_row:             '@SonataAdmin/CRUD/list_inner_row.html.twig'
        base_list_field:            '@SonataAdmin/CRUD/base_list_field.html.twig'
        pager_links:                '@SonataAdmin/Pager/links.html.twig'
        pager_results:              '@SonataAdmin/Pager/results.html.twig'
