server {
    listen 80;
    listen 443 ssl;
    ssl_certificate     /etc/nginx/ssl/cv.crt;
    ssl_certificate_key /etc/nginx/ssl/cv.key;
    server_name cv.my cv.com;
    index index.php index.html;

    root /var/www/html/public;

    access_log  /var/log/nginx/access.log;
    error_log   /var/log/nginx/error.log;

    client_max_body_size 256m;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
    gzip_min_length 1024;
    gzip_comp_level 5;

    location ~* \.(jpg|jpeg|gif|css|png|js|ico|html|svg|woff|woff2|ttf|eot|otf)$ {
        access_log off;
        expires max;
        log_not_found off;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param HTTPS on;
        fastcgi_param HTTP_X_FORWARDED_PROTO https;
        fastcgi_read_timeout 600s;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }
}
