parameters:
    app.transliterate.log_name: '%env(TRANSLITERATE_LOG_NAME)%'
    app.transliterate.log_file: '%env(TRANSLITERATE_LOG_FILE)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Service\TransliterateService:
        arguments:
            $logName: '%app.transliterate.log_name%'
            $logger: '@monolog.logger.transliterate'

    admin.post:
        class: App\Admin\PostAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Post, manager_type: orm, label: 'Posts' }
