services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    admin.post:
        class: App\Admin\PostAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Post, manager_type: orm, label: 'Posts' }
